Рефакторинг и убран roboflow
SergTyapkin/thaumcraft-auto-researcher pull request #10
Opened 2024-11-08 13:13 UTC by Limuranius

2024-11-13 04:45 UTC, SergTyapkin requested changes
Большущее спасибо за разбор сущностей кода по файлам. 

Очень круто, что добавлены всякие декораторы к классам, где это уместно

Но во многих местах есть (на мой взгляд) бесполезный линтинг кода, от которого его становится читать даже чуть менее приятно. Переносы строк мне кажутся излишними при работе с вычислениями и координатами. В этом случае, зачастую, бывает даже сложнее читать этот код быстро

(В общем где я поругался на переносы, можешь пж вернуть как было, и поправить один импорт?)

2024-11-13 04:45 UTC, SergTyapkin commented on src/UI/OverlayUI.py
> -from src.UI.UIPrimitives import Point, Line, Rect, Text, Image, UIPrimitive
Верни как было) Там же есть init-файл

2024-11-13 04:45 UTC, SergTyapkin commented on pyinstaller_configs/autoPyToExe.json
> +   "optionDest": "pathex",
А зачем это?

2024-11-13 04:45 UTC, SergTyapkin commented on src/UI/OverlayUI.py
> +                                                                       event.x() - self.lastMouseMovePoint[0]))
Ну кто просил тут линтинг устраивать то. Это читается хуже чем было вообще

2024-11-13 04:45 UTC, SergTyapkin commented on src/UI/OverlayUI.py
> +                        (obj.isHover(event.x(), event.y())) and
Двойной отступ?... Зачем а главное нахуя)

2024-11-13 04:45 UTC, SergTyapkin commented on src/controllers/Scenarios.py
> +            deg30HexagonsLines[idx].S.y = rectHexagonsCC.y + sin(pi / 6) * rad - (i < 0) * i * slotSizeY / 2 - (
Ну вот тебе так правда легче читать это?
Когда все строчки вокруг в одну написаны, а две посередине с переносами. Это ж не удобно

2024-11-13 04:45 UTC, SergTyapkin commented on src/logic/onnx_inference.py
> +import numpy as np
Я надеюсь, ты взял этот файл откуда-то, а не сам писал? Иначе это слишком круто

2024-11-21 00:56 UTC, Limuranius commented on pyinstaller_configs/autoPyToExe.json
> +   "optionDest": "pathex",
У меня в экзешнике были проблемы с импортами модулей. Как я понял, файл запускался из src/main.py, и путь этого файла считался корневым. А в модулях есть импорты вроде from `src.utils.LinkableValue import editLinkableValue` и питон не мог найти, что за src. Поэтому дополнительно добавил в пути корневую папку всего проекта. Хз, может я как-то не так собрал экзешник (вроде делал всё по инструкции), но у вас до этого всё работало, а у меня ложится

2024-11-25 11:11 UTC, Limuranius commented on src/UI/OverlayUI.py
> +                                                                       event.x() - self.lastMouseMovePoint[0]))
Сорри, у меня эти изменения автоматически сделал Pycharm, а я не заметил, когда коммитил. Вернул

2024-11-25 11:13 UTC, Limuranius commented on src/logic/onnx_inference.py
> +import numpy as np
Копировал код из кода roboflow, но пришлось повозиться и поубирать лишний функционал и абстаркции

2024-11-25 11:17 UTC, Limuranius commented
Да, мне потребовалось две недели, чтобы убрать пару переносов строк) 
Pycharm подставил со своим автоматическим форматированием, теперь буду знать, что и такое бывает

2025-01-31 11:22 UTC, closed without merging